const bibleIndexFull = {
    chapter:{
        es: 'Capítulo',
        en: 'Chapter'
    },
    es:[
        "Génesis",
        "Éxodo",
        "Levítico",
        "Números",
        "Deuteronomio",
        "Josué",
        "Jueces",
        "Rut",
        "1 Samuel",
        "2 Samuel",
        "1 Reyes",
        "2 Reyes",
        "1 Crónicas",
        "2 Crónicas",
        "Esdras",
        "Nehemías",
        "Ester",
        "Job",
        "Salmos",
        "Proverbios",
        "Esclesiastés",
        "Cantares",
        "Isaías",
        "Jeremías",
        "Lamentaciones",
        "Ezequiel",
        "Daniel",
        "Oseas",
        "Joel",
        "Amós",
        "Abdías",
        "Jonás",
        "Miqueas",
        "Nahum",
        "Habacuc",
        "Sofonías",
        "Hageo",
        "Zacarías",
        "Malaquías",
        "Mateo",
        "Marcos",
        "Lucas",
        "Juan",
        "Hechos",
        "Romanos",
        "1 Corintios",
        "2 Corintios",
        "Gálatas",
        "Efesios",
        "Filipenses",
        "Colosenses",
        "1 Tesalonicenses",
        "2 Tesalonicenses",
        "1 Timoteo",
        "2 Timoteo",
        "Tito",
        "Filemón",
        "Hebreos",
        "Santiago",
        "1 Pedro",
        "2 Pedro",
        "1 Juan",
        "2 Juan",
        "3 Juan",
        "Judas",
        "Apocalipsis"],
    en:[
        "Genesis",
        "Exodus",
        "Leviticus",
        "Numbers",
        "Deuteronomy",
        "Joshua",
        "Judges",
        "Ruth",
        "1 Samuel",
        "2 Samuel",
        "1 Kings",
        "2 Kings",
        "1 Chronicles",
        "2 Chronicles",
        "Ezra",
        "Nehemiah",
        "Esther",
        "Job",
        "Psalms",
        "Proverbs",
        "Ecclesiastes",
        "Song of songs",
        "Isaiah",
        "Jeremiah",
        "Lamentations",
        "Ezekiel",
        "Daniel",
        "Hosea",
        "Joel",
        "Amos",
        "Obadiah",
        "Jonah",
        "Micah",
        "Nahum",
        "Habakkuk",
        "Zephaniah",
        "Haggai",
        "Zechariah",
        "Malachi",
        "Matthew",
        "Mark",
        "Luke",
        "John",
        "Acts",
        "Romans",
        "1 Corinthians",
        "2 Corinthians",
        "Galatians",
        "Ephesians",
        "Philippians",
        "Colossians",
        "1 Thessalonians",
        "2 Thessalonians",
        "1 Timothy",
        "2 Timothy",
        "Titus",
        "Philemon",
        "Hebrews",
        "James",
        "1 Peter",
        "2 Peter",
        "1 John",
        "2 John",
        "3 John",
        "Jude",
        "Revelation"]
};

export default bibleIndexFull;