import { BibleIndex } from './interfaces/bibleIndex';

export const bibleIndexFull: BibleIndex = {
  en: {
    book: 'Book',
    chapter: 'Chapter',
    chapters: 'Chapters',
    verses: 'Verses',
    books: [
      'Genesis',
      'Exodus',
      'Leviticus',
      'Numbers',
      'Deuteronomy',
      'Joshua',
      'Judges',
      'Ruth',
      '1 Samuel',
      '2 Samuel',
      '1 Kings',
      '2 Kings',
      '1 Chronicles',
      '2 Chronicles',
      'Ezra',
      'Nehemiah',
      'Esther',
      'Job',
      'Psalms',
      'Proverbs',
      'Ecclesiastes',
      'Song of songs',
      'Isaiah',
      'Jeremiah',
      'Lamentations',
      'Ezekiel',
      'Daniel',
      'Hosea',
      'Joel',
      'Amos',
      'Obadiah',
      'Jonah',
      'Micah',
      'Nahum',
      'Habakkuk',
      'Zephaniah',
      'Haggai',
      'Zechariah',
      'Malachi',
      'Matthew',
      'Mark',
      'Luke',
      'John',
      'Acts',
      'Romans',
      '1 Corinthians',
      '2 Corinthians',
      'Galatians',
      'Ephesians',
      'Philippians',
      'Colossians',
      '1 Thessalonians',
      '2 Thessalonians',
      '1 Timothy',
      '2 Timothy',
      'Titus',
      'Philemon',
      'Hebrews',
      'James',
      '1 Peter',
      '2 Peter',
      '1 John',
      '2 John',
      '3 John',
      'Jude',
      'Revelation',
    ],
  },
  es: {
    book: 'Libro',
    chapter: 'Capítulo',
    chapters: 'Capítulos',
    verses: 'Versículos',
    books: [
      'Génesis',
      'Éxodo',
      'Levítico',
      'Números',
      'Deuteronomio',
      'Josué',
      'Jueces',
      'Rut',
      '1 Samuel',
      '2 Samuel',
      '1 Reyes',
      '2 Reyes',
      '1 Crónicas',
      '2 Crónicas',
      'Esdras',
      'Nehemías',
      'Ester',
      'Job',
      'Salmos',
      'Proverbios',
      'Esclesiastés',
      'Cantares',
      'Isaías',
      'Jeremías',
      'Lamentaciones',
      'Ezequiel',
      'Daniel',
      'Oseas',
      'Joel',
      'Amós',
      'Abdías',
      'Jonás',
      'Miqueas',
      'Nahum',
      'Habacuc',
      'Sofonías',
      'Hageo',
      'Zacarías',
      'Malaquías',
      'Mateo',
      'Marcos',
      'Lucas',
      'Juan',
      'Hechos',
      'Romanos',
      '1 Corintios',
      '2 Corintios',
      'Gálatas',
      'Efesios',
      'Filipenses',
      'Colosenses',
      '1 Tesalonicenses',
      '2 Tesalonicenses',
      '1 Timoteo',
      '2 Timoteo',
      'Tito',
      'Filemón',
      'Hebreos',
      'Santiago',
      '1 Pedro',
      '2 Pedro',
      '1 Juan',
      '2 Juan',
      '3 Juan',
      'Judas',
      'Apocalipsis',
    ],
  },
  fr: {
    book: 'Livre',
    chapter: 'Chapitre',
    chapters: 'Chapitres',
    verses: 'Versets',
    books: [
      'Genèse',
      'Exode',
      'Lévitique',
      'Nombres',
      'Deutéronome',
      'Josué',
      'Juges',
      'Ruth',
      '1 Samuel',
      '2 Samuel',
      '1 Rois',
      '2 Rois',
      '1 Chroniques',
      '2 Chroniques',
      'Esdras',
      'Néhémie',
      'Esther',
      'Job',
      'Psaumes',
      'Proverbs',
      'Ecclésiastes',
      'Cantique',
      'Ésaïe',
      'Jérémie',
      'Lamentations',
      'Ézéchiel',
      'Daniel',
      'Osée',
      'Joël',
      'Amos',
      'Abdias',
      'Jonas',
      'Michée',
      'Nahum',
      'Habacuc',
      'Sophonie',
      'Aggée',
      'Zacharie',
      'Malachie',
      'Matthieu',
      'Marc',
      'Luc',
      'Jean',
      'Actes',
      'Romains',
      '1 Corinthiens',
      '2 Corinthiens',
      'Galates',
      'Éphésiens',
      'Philippiens',
      'Colossiens',
      '1 Thessaloniciens',
      '2 Thessaloniciens',
      '1 Timothée',
      '2 Timothée',
      'Tite',
      'Philémon',
      'Hébreux',
      'Jaques',
      '1 Pierre',
      '2 Pierre',
      '1 Jean',
      '2 Jean',
      '3 Jean',
      'Jude',
      'Apocalypse',
    ],
  },
  zh: {
    book: '书',
    chapter: '章节',
    chapters: '章节数',
    verses: '诗句数',
    books: [
      '创世纪',
      '出埃及记',
      '利未记',
      '民数记',
      '申命记',
      '约书亚记',
      '士师记',
      '路得记',
      '撒母耳记上',
      '撒母耳记下',
      '列王纪上',
      '列王纪下',
      '历代志上',
      '历代志下',
      '以斯拉记',
      '尼希米记',
      '以斯帖记',
      '约伯记',
      '诗篇',
      '箴言',
      '传道书',
      '雅歌',
      '以赛亚书',
      '耶利米书',
      '耶利米哀歌',
      '以西结书',
      '但以理书',
      '何西阿书',
      '约珥书',
      '阿摩司书',
      '俄巴底亚书',
      '约拿书',
      '弥迦书',
      '那鸿书',
      '哈巴谷书',
      '西番雅书',
      '哈该书',
      '撒迦利亚书',
      '玛拉基书',
      '马太福音',
      '马可福音',
      '路加福音',
      '约翰福音',
      '使徒行传',
      '罗马书',
      '哥林多前书',
      '哥林多后书',
      '加拉太书',
      '以弗所书',
      '腓立比书',
      '歌罗西书',
      '帖撒罗尼迦前书',
      '帖撒罗尼迦后书',
      '提摩太前书',
      '提摩太后书',
      '提多书',
      '腓利门书',
      '希伯来书',
      '雅各书',
      '彼得前书',
      '彼得后书',
      '约翰一书',
      '约翰二书',
      '约翰三书',
      '犹大书',
      '启示录',
    ],
  },
};

export const helpLanguages = {
  en:
    'Available commands:\n' +
    'command: <code>help</code>\n' +
    'action: Displays this help.\n\n' +
    'command: <code>index</code>\n' +
    'action: Displays the index of the Bible.\n\n' +
    'command: <code>index OSIS-ID</code>\n' +
    'action: Displays the chapters and their number of verses from a book ' +
    'by its OSIS ID. You can see the OSIS IDs with the "index" command.\n' +
    'e.g.\n' +
    '<code>index Gen</code>\n\n' +
    'command: <code>(your citation)</code>\n' +
    'action: Displays the citation between the parenthesis' +
    ' in the specified version, or the default version if ' +
    "there's no specified version.\n" +
    'e.g.\n' +
    '<code>(Genesis 1:1)</code>\n\n' +
    'command: <code>version "VER"</code>\n' +
    'action: Changes the version for the following citations.\n' +
    'e.g.\n' +
    '<code>version "KJV"\n' +
    '(Genesis 1:1)</code>\n\n' +
    'command: <code>versions "VER-1", "VER-2", "VER-N"</code>\n' +
    'action: Displays the following citations on multiple versions.\n' +
    'e.g.\n' +
    '<code>versions "KJV", "RVR"\n' +
    '(Genesis 1:1)\n' +
    '(John 3:16)</code>\n\n' +
    'command: <code>versions "VER-1", "VER-2", "VER-N" par</code>\n' +
    'action: Displays the following citations on multiple versions ' +
    'in parallel columns.\n' +
    'e.g.\n' +
    '<code>versions "KJV", "RVR" par\n' +
    '(Genesis 1:1)\n' +
    '(John 3:16)</code>',
};
